const db = require('../../db-connection');

const jwt = require("jsonwebtoken");
const bcrypt = require("bcryptjs");
const { promisify } = require('util');

// Promisify the db.query method for async/await use
const query = promisify(db.query).bind(db);

const User = {};

User.addUser = async (newUser, res, result) => {
    console.log("&&&");
    global.userId = newUser.UserID;

    // Basic validation
    if (!newUser.Username || !newUser.Email || !newUser.Password || !newUser.Role) {
        return res.status(400).json({ message: 'Please provide name, email, password, and role' });
    }

    try {
        // Check if the user already exists
        const existingUsers = await query('SELECT * FROM user WHERE Email = ?', [newUser.Email]);
        if (existingUsers.length > 0) {
            return res.status(400).json({ message: 'User already exists' });
        }

        // Hash the password
        const hashedPassword = await bcrypt.hash(newUser.Password, 10);
        console.log(hashedPassword);
        console.log("!!");

        // Create new user object
        const newUser1 = {
            UserID: newUser.UserID, // Assuming UserID is provided; it might be auto-generated by the DB
            Username: newUser.Username,
            Email: newUser.Email,
            Password: hashedPassword,
            Role: newUser.Role
        };

        // Insert the new user into the database
        const insertResult = await query('INSERT INTO user SET ?', newUser1);

        // Generate JWT token
        const payload = { UserID: newUser.UserID, Username: newUser.Username, Role: newUser.Role };
        console.log(payload);
        const token = jwt.sign(payload, process.env.SECRET_KEY, { expiresIn: '1h' });

        // Send success response
        return res.status(201).json({ message: 'User registered successfully', token, user: newUser1 });

        // The following line is unnecessary with async/await
        // result(null, { ...newUser1, id: insertResult.insertId });
    } catch (error) {
        console.error('Error:', error);

        // Send error response if something goes wrong
        return res.status(500).json({ message: 'Internal server error' });
    }
};

User.login = async (User, res, result)=>{
    const { email, password } = User;
    console.log(email);
    console.log(password);
    try {
        // Check if the user already exists
        const existingUsers = await query('SELECT * FROM user WHERE Email = ?', [email]);
        console.log(existingUsers);
        if (existingUsers.length == 0) {
            return res.status(400).json({ message: 'User not found' });
        }
        console.log(password);
        console.log(existingUsers[0].Password);
        const isMatch = await bcrypt.compare(password, existingUsers[0].Password);

        console.log(isMatch);
        if (!isMatch) return res.status(400).json({ message: 'Invalid credentials' });

    
        // Generate JWT token
        const payload = { UserID: existingUsers[0].UserID, Username: existingUsers[0].Username, Role: existingUsers[0].Role };
        console.log(payload);
        const token = jwt.sign(payload, process.env.SECRET_KEY, { expiresIn: '1h' });

        // Send success response
        return res.status(201).json({ message: 'User Login successfully', token, user: existingUsers[0] });

        // The following line is unnecessary with async/await
        // result(null, { ...newUser1, id: insertResult.insertId });
    } catch (error) {
        console.error('Error:', error);

        // Send error response if something goes wrong
        return res.status(500).json({ message: 'Internal server error' });
    }
}

User.getUserList = (result) => {

    db.query('SELECT * FROM user', (err, res) => {

        if (err) {
            console.log(3);
            result(err, null);
            return;
        }
        result(null, res);
    });
};

User.getUserListById = (UserID, result) => {

    db.query(`SELECT * FROM user WHERE UserID = ${UserID}`, (err, res) => {

        if (err) {
            console.log(3);
            result(err, null);
            return;
        }
        result(null, res);
    });
};

User.getUserListByName = (Username, result) => {
    db.query(`SELECT * FROM user WHERE Username = "${Username}"`, (err, res) => {

        if (err) {
            console.log(3);
            result(err, null);
            return;
        }
        result(null, res);
    });
};

User.getUserListByEmail = (email, result) => {

    db.query(`SELECT * FROM user WHERE Email = "${email}"`, (err, res) => {

        if (err) {
            console.log(3);
            result(err, null);
            return;
        }
        result(null, res);
    });
};


User.updateUser = (UserID, Data, result) => {

    const userData = db.query(`SELECT * FROM user Where UserID = ${UserID}`, (err, res) => {

        if (err) {
            console.log(3);
            result(err, null);
            return;
        }
        console.log(res);
        let updateQuery = 'UPDATE user SET ';
        Object.keys(Data).forEach((key, index) => { // Object.keys(Data) is used for iterate key-values 
            if (Data[key] !== '') {
                updateQuery += `${key} = '${Data[key]}'`;
                if (index < Object.keys(Data).length - 1) {
                    updateQuery += ', ';
                }
            }
        });
        updateQuery += ` WHERE UserID = ${UserID}`;
        console.log(updateQuery);
        // Execute the update query
        db.query(updateQuery, (err, result) => {
            if (err) {
                console.error('Error updating record:', err);
                return;
            }
            console.log('Record updated successfully');
        });

        result(null, res);

    });

}


User.deleteUser = (UserID, result) => {
    db.query(`DELETE FROM user WHERE UserID = "${UserID}"`, (err, res) => {

        if (err) {
            console.log(3);
            result(err, null);
            return;
        }
        result(null, res);
    });
}
module.exports = User;  